= API keys

User authentication and authorisation (for those TED APIs that require it) is controlled by the use of API keys. TED API keys are essentially UUIDs (Universally Unique Identifiers) without hyphens (dashes). 

You can generate and manage your own API keys by logging-in to your account in the link:https://developer.ted.europa.eu[**TED Developer Portal**]footnote:portal[{dev-portal}].

If you use the Publication API, after you generate your key, log into the link:https://enotices2.ted.europa.eu[eNotices2 website] at least once to pair your account and perform at least one valid API request for the system to recognise you as an "eSender".

NOTE: Only one API key is allowed per user. The creation of a new API key implies the automatic revocation of the previous one.

== Getting started

. Obtain an API key
* [ ] Visit the https://developer.ted.europa.eu/home[**TED Developer Portal**].
* [ ] Log in with your **EU Login** credentials.
* [ ] Generate your API Key via the *Manage API Keys* section.

NOTE: Copy and save your API key upon creation; it cannot be retrieved later.

NOTE: The Search API does not require a key.

[start=2]
. Authenticate Your Application
* [ ] Use your API Key in the header of requests to access TED services.

. Test in the https://docs.ted.europa.eu/eforms-common/preview/index.html[eForms Preview Environment]
* [ ] Do not test in the Production environment, as it is reserved for notices that will be published on TED.
* [ ] For more information, see section <<Testing your apps>>.

IMPORTANT: eSenders and developers can create multiple accounts in the Preview environment for testing. In the Production environment, only one account and one API key per EU Login are allowed. We strongly recommend using a shared or functional email address for setting up Production accounts instead of a personal email.

More information on API key management can be found xref:api.adoc[here]


== API key generation

You can generate an API Key by logging into the TED Developer Portalfootnote:portal[] and clicking on the "Manage your API Keys" button. To login to the TED Developer Portal you will need a valid EU Loginfootnote:eu-login[{eu-login}] account. 

NOTE: For security reasons API keys are not stored and cannot be retrieved via the TED Developer Portal after they are generated. Your API key will be delivered to you only at the time of generation. Copy and safely store the provided API key; if you lose it, you will have to generate a new one.


== API key life span


* **Expiry:**
  - Every API key is valid for 24 months.
  - After its validity period elapses, the API key expires.

* **Renewal:**
  - API key renewal extends the validity of an API key for 12 months.
  - An automated notification will be sent four (4) weeks before expiration to the email associated with the EU-Login account used to create the API key.
  - The email contains a hyperlink for renewing the API key. If not clicked within 21 days, the link expires, and a new email will be sent with a fresh hyperlink.

* **Revocation:**
  - You can revoke any unused API keys as needed in the TED Developer Portal.
  - Revoked API keys are invalidated permanently.

