= Conversion API 

As eForms replaced legacy TED XML notices, the Conversion API simplified this transition by enabling systems to convert older formats automatically into partial eForms notices. By converting legacy TED XML notices into current eForms notices, the API facilitates continuity and consistency in managing procurement information.

== Available Operations

//[.doc h3]
//* Convert TED XML Notices

=== Convert TED XML Notices

This operation allows users to convert notices from the legacy TED XML format to draft eForms. Primarily used by eNotices2, it facilitates the import of TED XML notices, enabling users to seamlessly continue procedures in eForms initiated with the old schema. After conversion, users can complete the draft notices with additional information required by eForms. Developers can also use this stand-alone API for integration, assisting in the migration process to eForms by supporting partial conversions.


==== API Request
[source]
----
POST /v3/notices/convert
----

==== Swagger API Endpoints

- **Preview Environment:**  
  link:https://api.preview.ted.europa.eu/swagger-ui/index.html#/Conversion/convertNotice[Access the Swagger API Interface]

- **Production Environment:**  
  link:https://api.ted.europa.eu/swagger-ui/index.html#/Conversion/convertNotice[Access the Swagger API Interface]


== Who Uses This API 

* *eSenders*: Migrating legacy data to the eForms ecosystem.
* *Developers*: Managing legacy procurement notices programmatically.
* *eNotices2 Users*: Importing published TED XML notices to continue procedures. 

'''

Explore the full documentation here: https://github.com/OP-TED/ted-xml-data-converter 

////
'''
----
POST /v3/notices/convert    Convert TED XML notices into partial eForms notices
----

==== What It Does

* Transforms legacy TED XML notices into "partial" eForms notices, which users can complete and submit. 
* Bridges the gap between legacy systems and the eForms standard in use today. 

== Who Uses This API 

* eSenders: Migrating legacy data to the eForms ecosystem.
* Developers: Managing legacy procurement notices programmatically.
* eNotices2 Users: Importing published TED XML notices to continue procedures. 

Explore the full documentation here: https://github.com/OP-TED/ted-xml-data-converter 
