CAUTION: Please refrain from testing in the Production environment of eNotices2. This is reserved for notices that will be published in TED. TED Apps for eForms are available in the link:https://docs.ted.europa.eu/home/eforms/preview/index.html[Preview environment] for testing purposes. If you are an eSender, please note that URLs and API keys in "Production" and "Preview" environments are not interchangeable.



:eu-login: EU Login is the European Commission's user authentication service. It allows authorised users to access a wide range of Commission web services, using a single email address and password. If you don't have one, you can link:https://ecas.ec.europa.eu/cas/eim/external/register.cgi[create an EU Login account here].

:dev-portal: The link:https://developer.ted.europa.eu[TED Developer Portal] is the single point of access for all TED developers.

= TED API Documentation

TED API allows application developers to connect their 3rd party applications to the TED web services. Using TED APIs you can create applications that:

 * Search for and retrieve published notices from the TED Website,
 * Submit new public procurement notices for publication,
 * Validate or render notices.

TED API allows anonymous access to all services manipulating published notices (i.e. searching for, or retrieving notices already published on TED). These APIs are mostly targeted to data reusers. You can find information on reusing TED data at the link:https://ted.europa.eu/en/simap/developers-corner-for-reusers#search-retrieve-data[Developers' Corner].

All TED APIs manipulating notices that are not yet published, require the \cas\logincaller to be authenticated with an API key.


== API keys

User authentication and authorisation (for those TED APIs that require it) is controlled with the use of API keys. TED API keys are essentially UUIDs (Universally Unique Identifiers), without hyphens (dashes). 

You can generate and manage your own API keys by logging-in to your account in the link:https://developer.ted.europa.eu[**TED Developer Portal**]footnote:portal[{dev-portal}].

If you use the the eNotices2 API, after you generate your key, please log into the link:https://enotices2.ted.europa.eu[eNotices2 website] at least once to pair your account.

NOTE: Only one API key is allowed per user. The creation of a new API key implies the automatic revocation of the previous one.


=== API key generation

You can generate an API Key by logging into the TED Developer Portalfootnote:portal[] and clicking on the "Manage your API Keys" button. To login to the TED Developer Portal you will need a valid EU Loginfootnote:eu-login[{eu-login}] account. 

NOTE: For security reasons API keys are not stored and cannot be retrieved via the TED Developer Portal after they are generated. Your API key will be delivered to you only at the time of generation. Copy and safely store the provided API key. If you lose it you will have to generate a new one.


=== API key lifetime

Expiry:: Every API key is valid for 24 months. After its validity period elapses, the API key expires. 

Renewal:: 
API key renewal extends the validity of an API key for 12 months. 
+ 
An automated notification will be sent four (4) weeks before the expiration of the API key to the email address associated with the EU-Login account of the user that created the API key. The email will contain a hyperlink that can be used to renew the API key. If you don't click on the hyperlink within 21 days, the link will expire and a new email will be sent to you with a new hyperlink.

Revocation:: You can revoke any unused API keys as needed in the TED Developer Portal. Revoked API keys are invalidated permanently.

== Available APIs

You can find below the Swagger pages documenting the TED API endpoints that are currently available in production:

Validation:: Validate notices, get validation report. + 
https://cvs.ted.europa.eu/swagger-ui/index.html

Publication:: Submit notices; search submitted notices; stop publication: + 
https://enotices2.ted.europa.eu/esenders/webjars/swagger-ui/index.html

Visualisation:: Render notices in PDF or HTML: + 
https://viewer.ted.europa.eu/swagger-ui/index.html

== Testing your apps
An **eForms Preview Environment** is available to allow and encourage developers to test their applications. You can find more xref:home:eforms:preview/index.adoc[details on the eForms Preview Environment here].

CAUTION: To use the eForms Preview Environment you will need an API key generated using the link:https://developer.preview.ted.europa.eu/home[TED Developer Portal of the Preview Environment]. This means that you will also need an EU Login account from the link:https://ecas.acceptance.ec.europa.eu/cas/login[EU-Login Acceptance Environment].

NOTE: Information about eSentool, the legacy API to submit and manage notices, is available on the link:https://webgate.ec.europa.eu/fpfis/wikis/display/TEDeSender[legacy eSenders Wiki].

== Status & Roadmap

The TED API endpoints currently available are the first generation of APIs for the new TED web services for eForms. 

These APIs have been initially released in June 2022 together with the "eForms Preview Environment" and have since remained unchanged. These endpoints will also remain unchanged throughout their lifetime. 

We are currently in the process of simplifying, better documenting and rationalising our APIs to improve user experience and to allow us to keep enriching them in the future for offering better and consistent services to our developer community. 

A second generation of TED APIs is being developed. The release of this second version of TED APIs (which will be known as TED API v2) will be added next to the currently available endpoints and will not replace them. This will allow 3rd party applications that already use the current endpoints to continue functioning **undisrupted**. The current endpoints will only be discontinued when no 3rd party applications use them any more.
