

= Publication API  

The Publication API allows users and systems to programmatically submit notices for publication on TED using an API key. With this key, users can also query their own submitted notices, stop the publication process, or retrieve validation reports. Connecting with the eNotices2 system and the TED Central Validation Service, this API enables eSenders and public authorities to process notices efficiently and at scale.


== Available Operations

//[.doc h3]
//* Query Submitted Notices

=== Query Submitted Notices

This operation enables users to query the status and details of their submitted notices. API users can access a paginated list of all their submitted notices, which they can filter and sort based on relevant criteria. Access is exclusive to the user's own submissions, requiring an API key. Additionally, this operation facilitates the synchronization of important metadata, such as publication status, during the notice management process.


==== API Request
[source]
----
GET /v3/notices/
----

==== Swagger API Endpoint 
https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

=== Stop Publication of Submitted Notice

This API operation enables users to stop the publication process for a notice they have submitted. This action must be taken before the notice is exported to TED, as the publication process becomes irreversible at that point. Halting a notice in time prevents it from being published, offering control over the publication timeline. Once a notice reaches the "publishing" status, it cannot be stopped.



==== API Request
[source]
----
POST /v3/notices/{businessId}/stop-publication
----


==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

=== Retrieve Validation Report for Submitted Notice

Every submitted eForms notice undergoes a validation process to ensure compliance with regulatory business rules; this results in a report even if the notice does not pass validation successfully. This API operation enables users to obtain the validation report generated during their notice submission. It ensures users can review and address any validation issues identified during the submission.


==== API Request
[source]
----
GET /v3/notices/{businessId}/validation-report
----

==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

'''

=== Submit New Notices for Publication on TED

This API operation enables users to programmatically submit new notices in XML format for publication. The notice must have a unique identifier and meet specific requirements, such as including a valid notice author email and the preferred language for notifications. The email identifies the responsible party, such as the Contracting Authority, and the language must be an official EU language. Upon submission, the notice is validated against a set of business rules. If it successfully passes, it is marked "SUBMITTED" and becomes eligible for publication. If it fails, it is marked "VALIDATION_FAILED" and cannot be published.


==== API Request
[source]
----
POST /v3/notices/submit
----

==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice

== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities.
* *Public Authorities*: Handling their own procurement notices through connected applications.

////

= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects to the eNotices2 system to provide programmatic control over the publication process. 

== Available operations

[.hlist]
* Query submitted notices

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;testing indents

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/			        
----

[.indent2]
==== What It Does
* Enables synchronization of notice metadata, such as publication status, during the publication process. 

[.indent2]
==== Swagger API Endpoint 
* https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

[.hlist]
* Request to stop the publication of submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/{businessId}/stop-publication	
----

[.indent2]
==== What It Does
* Stops the publication of notices that are successfully submitted but not yet published. 

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

[.hlist]
* Retrieve validation report for submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/{businessId}/validation-report	
----

[.indent2]
==== What It Does
* Provides the validation report that is created when a notice is submitted for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

'''

[.hlist]
* Submit new notices for publication on TED

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/submit			        
----

[.indent2]
==== What It Does
* Allows programmatic submission of notices for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice







=== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities. 
* *Public Authorities*: Handling their own procurement notices through connected applications. 
////
