= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects with the eNotices2 system to provide programmatic control over the publication process. 

== Available Operations 
* Allows programmatic submission of notices for publication.  
* Stops publication of notices that have been successfully submitted but not yet published. 
* Retrieves the validation reports of one’s own submitted notices. 
* Enables querying of one’s own submitted notices allowing synchronisation of the notice metadata, e.g. a notice status during the publication process. 

== Why This API Exists
The Publication API automates the handling of procurement notices, reducing reliance on manual processes. It empowers eSenders and public authorities to manage notices efficiently at scale.

== Endpoint

[source]
----
POST /v3/notices/submit			        Submit new notices for publication on TED
POST /v3/notices/{businessId}/stop-publication	Request to stop the publication of submitted notice
GET /v3/notices/{businessId}/validation-report	Retrieve validation report for submitted notice
GET /v3/notices/			        Query submitted notices

----  

== Who Uses This API
* eSenders managing notices on behalf of contracting authorities. 
* Public authorities managing their own procurement notices through an application that connects to the Publication API 
