

= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects to the eNotices2 system to provide programmatic control over the publication process.

== Available Operations

[.hlist]
* Query Submitted Notices

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This operation allows API users to access a paginated list of all the notices they have submitted. Users can filter and sort these notices based on relevant criteria. Access is exclusive to the user's own submissions, providing full insight into their notices. Additionally, it facilitates the synchronization of important metadata, such as publication status, during the notice management process.operation allows you to query the status and details of submitted notices.

[.indent2]
==== API Request
[source]
----
GET /v3/notices/
----

[.indent2]
==== Swagger API Endpoint 
https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

[.hlist]
* Stop Publication of Submitted Notice

This API operation allows API users to stop the publication process for a notice they have submitted. It must be done before the notice is exported to TED, at which point the publication process becomes irreversible. If a notice is halted in time, it prevents the notice from being published, offering control over the publication timeline. Once a notice reaches the "publishing" status, it cannot be stopped.

[.indent2]
==== API Request
[source]
----
POST /v3/notices/{businessId}/stop-publication
----

[.indent2]
==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

[.hlist]
* Retrieve Validation Report for Submitted Notice

[.indent2]
Every submitted eForms notice undergoes a validation process to ensure it complies with regulatory business rules, resulting in a report even if it does not successfully pass validation. This API operation allows API users to obtain the validation report generated during the submission of their notice. It ensures users can review and address any validation issues identified during the submission.

[.indent2]
==== API Request
[source]
----
GET /v3/notices/{businessId}/validation-report
----

[.indent2]
==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

'''

[.hlist]
* Submit New Notices for Publication on TED

[.indent2]
This API operation allows users to programmatically submit new notices in XML format for publication. The notice must have a unique identifier and meet specific requirements, such as including a valid notice author email and the preferred language for notifications. The email identifies the responsible party, like the Contracting Authority, while the language must be an official EU language. Upon submission, the notice is validated against a set of business rules. If it successfully passes, it is marked "SUBMITTED" and eligible for publication. If it fails, it is marked "VALIDATION_FAILED" and cannot be published.

[.indent2]
==== API Request
[source]
----
POST /v3/notices/submit
----


[.indent2]
==== Swagger API Endpoint 
https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice

== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities.
* *Public Authorities*: Handling their own procurement notices through connected applications.


////

= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects to the eNotices2 system to provide programmatic control over the publication process. 

== Available operations

[.hlist]
* Query submitted notices

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;testing indents

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/			        
----

[.indent2]
==== What It Does
* Enables synchronization of notice metadata, such as publication status, during the publication process. 

[.indent2]
==== Swagger API Endpoint 
* https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

[.hlist]
* Request to stop the publication of submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/{businessId}/stop-publication	
----

[.indent2]
==== What It Does
* Stops the publication of notices that are successfully submitted but not yet published. 

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

[.hlist]
* Retrieve validation report for submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/{businessId}/validation-report	
----

[.indent2]
==== What It Does
* Provides the validation report that is created when a notice is submitted for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

'''

[.hlist]
* Submit new notices for publication on TED

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/submit			        
----

[.indent2]
==== What It Does
* Allows programmatic submission of notices for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice







=== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities. 
* *Public Authorities*: Handling their own procurement notices through connected applications. 
////
