= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects to the eNotices2 system to provide programmatic control over the publication process. 

== Available operations

[.hlist]
* Query submitted notices

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/			        
----

[.indent2]
==== What It Does

* Enables synchronization of notice metadata, such as publication status, during the publication process. 

[.indent2]
==== Swagger API Endpoint 
* https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

[.hlist]
* Request to stop the publication of submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/{businessId}/stop-publication	
----

[.indent2]
==== What It Does
* Stops the publication of notices that are successfully submitted but not yet published. 

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

[.hlist]
* Retrieve validation report for submitted notice

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
GET /v3/notices/{businessId}/validation-report	
----

[.indent2]
==== What It Does
* Provides the validation report that is created when a notice is submitted for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

'''
[.hlist]
* Submit new notices for publication on TED

[.indent2]
hello this is the intro

[.indent2]
==== API request
[source]
----
POST /v3/notices/submit			        
----

[.indent2]
==== What It Does
* Allows programmatic submission of notices for publication.  

[.indent2]
==== Swagger API Endpoint 
* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice







=== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities. 
* *Public Authorities*: Handling their own procurement notices through connected applications. 
