= Publication API  

The Publication API automates the management of procurement notices, enabling eSenders and public authorities to handle notices efficiently and at scale. This API connects with the eNotices2 system to provide programmatic control over the publication process. 


== Available operations 

[sidebar]
=== Query submitted notices

=== Introduction

hello this is the intro

=== Source code
[source]
----
GET /v3/notices/			        
----

=== What It Does

* Enables synchronization of notice metadata, such as publication status, during the publication process. 

=== Swagger API Endpoint 

* https://api.acceptance.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getNotices

'''

[sidebar]
Request to stop the publication of submitted notice

=== Introduction

hello this is the intro

=== Source code

[source]
----
POST /v3/notices/{businessId}/stop-publication	
----

=== What It Does

* Stops the publication of notices that are successfully submitted but not yet published. 

=== Swagger API Endpoint 

* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/stopPublication

'''

=== Retrieve validation report for submitted notice

==== Introduction

hello this is the intro

==== Source code
[source]
----
GET /v3/notices/{businessId}/validation-report	
----

==== What It Does

* Provides the validation report that is created when a notice is submitted for publication.  

==== Swagger API Endpoint 

* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Publication/getValidationReport

=== Submit new notices for publication on TED

==== Introduction

hello this is the intro

==== Source code
[source]
----
POST /v3/notices/submit			        
----

==== What It Does

* Allows programmatic submission of notices for publication.  

==== Swagger API Endpoint 

* https://api.ted.europa.eu/webjars/swagger-ui/index.html#/Endpoints/submitNotice







=== Who Uses This API
* *eSenders*: Managing notices on behalf of contracting authorities. 
* *Public Authorities*: Handling their own procurement notices through connected applications. 
