= Authentication API

Authentication API provides operation:

[source]
----
POST /v3/api-keys/{token}/renew	
----

* This operation extends the validity of an expiring https://docs.ted.europa.eu/api/index.html#_api_key_lifetime[API key].
* Parameter `token` is mandatory and it can be found in the hyperlink in the sent email with subject _[Ted Developer Portal] Your API key will soon expire, please renew it_.


= Conversion API

Conversion API provides operation:

[source]
----
POST /v3/notices/convert	
----

* This operation returns a partial eForms notice as a result of conversion of XML notice in the old https://github.com/OP-TED/ted-xml-data-converter#current-status[TED XML format]
* Request body contains notice content in TED XML format.
* `CustomizationID` element in the returned eForms notice is set to the latest value maintained for conversion and this value can change in time.



= Conversion API 

== Purpose 
Converts legacy TED XML notices into current eForms notices, to facilitate continuity and consistency in data. 

== What It Does

* Transforms legacy TED XML notice formats into "partial" eForms notices, which can then be completed by users. 
* Bridges the gap between legacy systems and the eForms standard that is currently in use. 

== Why This API Exists 
As eForms replaced legacy TED XML notices, the Conversion API simplifies the transition by enabling systems to convert older formats automatically. This ensures compatibility and preserves access to critical procurement data.  

== Endpoint 

[source]
----
POST /v3/notices/convert	 Convert TED XML notices into partial eForms notices. 	
----



== Who Uses This API 

* eSenders migrating legacy data to the eForms ecosystem. 
* Developers managing legacy procurement notices. 
* eNotices2 web user interface when users select to import a published TED XML notice to continue a procedure. 

Explore the full documentation here: https://github.com/OP-TED/ted-xml-data-converter 


= Search API

Search API provides operation:

[source]
----
POST /v3/notices/search	
----

* This operation returns list of published notices matching the search query and their data.
* Parameter `query` is mandatory and contains query description using https://ted.europa.eu/en/expert-search[expert search] syntax.
* Parameter `fields` is mandatory and contains list of fields to be returned with each notice matching the search query.
* Parameter `page` specifies a sequential number of the page to be returned from the search results with a pagination applied. If not specified, value 0 is used as default.
* Parameter `limit` specifies page size as number of results to be returned per page. If not specified, value 10 is used as default.
* Parameter `scope` specifies scope of search. (LATEST: only notices of the current OJ S release, ACTIVE: only active notices, ALL: all notices). If not specified, value LATEST is used as default.
* Parameter `checkQuerySyntax` specifies if the search is to be executed (false), or only the syntax of the query is to be checked, but the search query is not executed. When not specified, value false is used as default.
* Parameter `paginationMode` specifies type of pagination to be applied. The PAGE_NUMBER mode allows retrieval up to 15000 notices for a given query, using pagination. To retrieve more notices, it is possible to use the ITERATION mode. ITERATION mode does not have limitation on the number of retrievable notices, but in this case it is not possible to choose the specific page. The first request will return an iterationNextToken that should be provided to the next call of the search endpoint in order to retrieve the next result page. If not specified, PAGE_NUMBER value is used as default.
* Parameter `onlyLatestVersions` specifies if all versions of matching notices is to be returned, or only the latest versions. If not specified, value true is used as default.
* Parameter `iterationNextToken` specifies Opaque token returned by the previous call to the search endpoint to retrieve the next result page. It shouldn't be provided in PAGE_NUMBER mode or if this is the first request in ITERATION mode.



= Search API 

== Purpose 
Allows developers to search and retrieve published procurement notices and their data. 

== What It Does 
* Provides access to published notices via expert queries. 
* Enables bulk downloads of notices in XML format for analysis or reuse. 

== Why This API Exists
The Search API is mostly targeted to data reusers; it ensures transparency and accessibility by making publicly available procurement data easy to find and reuse. 

== Endpoint

[source]
----
POST /v3/notices/search		Search and retrieve published notices
----  

== Special Features

This API does not require authentication, making it accessible to any system or user. 

== Who Uses This API

* Commercial organisations providing added-value services to vendors and buyers by integrating TED data into their platforms. 
* Researchers analysing public procurement trends. 
* Developers creating transparency tools or reusing public data. 
* eNotices2 web interface when a user imports a notice from TED to continue a procedure. 
Explore the full documentation here: https://ted.europa.eu/en/simap/developers-corner-for-reusers[Developers' corner: APIs for your own integration - ted.europa.eu - TED]



= Validation API

Validation API provides 2 operations:

[source]
----
GET /v3/config/sdk-versions	
----

* This operation provides information on the set of currently https://docs.ted.europa.eu/eforms-common/active-versions/index.html#_terminology[active SDK] versions in JSON format. 
* It doesn't use any input parameter. 
* Information is valid at the moment when the operation is called and can be changed over the time.
* History of the changes cannot be retrieved, only the last update. 
* Information content and how to get the set of active SDK versions from it is described on the page https://docs.ted.europa.eu/eforms-common/active-versions/index.html#version-range[sdk-versions].

[source]
----
POST /v3/notices/validate
----

* This operation returns a https://docs.ted.europa.eu/eforms/latest/schematrons/index.html#_introduction[schematron] validation report which describes all the tests performed.
* Parameter `notice` is mandatory and contains notice content encoded in base64 string.
* Parameter `language` specifies language used for text messages related to failed assertions. If it is not specified, then "en" value is used as default.
* Parameter `validationMode` specifies https://docs.ted.europa.eu/eforms/latest/schematrons/index.html#_structure_of_schematron_folder_and_files[types of rules] applied for the validation. If it is not specified, then "static" value is used as default.
* Parameter `eFormsSdkVersion` specifies active SDK version against which the notice is being validated. If it is not specified, then value from `CustomizationID` element from the notice is used as default. 



= Validation API  

== Purpose 
Validate procurement notices to ensure compliance with EU standards and eForms regulations. 

== What It Does 
* Checks notices for errors (e.g., missing fields, incorrect values). 
* Issues/ Returns warnings for potential lawfulness concerns that require further human review. 

== Why This API Exists
The Validation API ensures notices meet mandatory legal and procedural standards at any time before or upon submission, preventing errors and reducing the risk of non-compliance.

== Endpoint

[source]
----
POST /v3/notices/validate		Validate notices for compliance at any time before or upon submission
----  

== Who Uses This API
* Developers ensuring notices meet requirements, especially before submission. 
* eSenders avoiding compliance errors during submission. 
* eNotices2 web interface for validating notices before or upon submission. 

Explore more about schematron rules and validation reports here: https://docs.ted.europa.eu/eforms/latest/schematrons/index.html#_structure_of_schematron_folder_and_files
