= Visualisation API  

The Visualisation API enables the rendering of procurement notices into user-friendly formats, such as PDFs or HTML. This functionality supports both internal workflows and public dissemination, making notices easier to read and share. 


== Available Operations

//[.doc h3]
//* Render Notices

=== Render Notices

The "/render" operation converts XML procurement notices into user-friendly formats like PDF or HTML, making the data easier to read and share. This API provides operations in two variants. For larger, more complex notices, the asynchronous API should be used to prevent request time-outs.  



==== API Request
[source]
----
POST /v3/notices/render
----

[source]
----
POST /v3/notices/render-async
----

==== Swagger API Endpoints

- **Preview Environment:**  
  * link:https://api.preview.ted.europa.eu/swagger-ui/index.html#/Visualisation/render[Swagger: Access Render Operation]
  * link:https://api.preview.ted.europa.eu/swagger-ui/index.html#/Visualisation/renderWithCallback[Swagger: Access Render With Callback Operation]

- **Production Environment:**  
  * link:https://api.ted.europa.eu/swagger-ui/index.html#/Visualisation/render[Swagger: Access Render Operation]
  * link:https://api.ted.europa.eu/swagger-ui/index.html#/Visualisation/renderWithCallback[Swagger: Access Render With Callback Operation]


== Who Uses This API

* *Organisations*: Integrating visualised notices into their platforms. 
* *TED developers*: Generating previews for notices. 
* *eNotices2 application*: For the rendering of notices via the web interface in PDF or HTML. 

'''
Explore more about view templates used in rendering here: https://docs.ted.europa.eu/eforms/latest/viewer-templates/index.html

////
