= Visualisation API  

== Purpose 
Render procurement notices into user-friendly formats for publication or internal use.

== What It Does 
* Converts XML notices into visually accessible formats like PDF or HTML. 

== Why This API Exists
The Visualisation API makes procurement notices easier to read and share by converting them into familiar formats. It supports both public dissemination and internal workflows.

== Endpoint

[source]
----
POST /v3/notices/render			Generate formatted notices (synchronous rendering)
POST /v3/notices/render-async 	Generate formatted notices (asynchronous rendering)
----  

== Note
This API provides operations in two variants. For larger, more complex notices, the asynchronous API should be used to prevent request time-outs.  

== Who Uses This API
* Organisations integrating visualised notices into their platforms. 
* TED developers generating previews for notices. 
* eNotices2 for the rendering of notices. 

Explore more about view templates used in rendering here: https://docs.ted.europa.eu/eforms/latest/viewer-templates/index.html
