= Visualisation API  

The Visualisation API enables the rendering of procurement notices into user-friendly formats, such as PDFs or HTML. This functionality supports both internal workflows and public dissemination, making notices easier to read and share. 


== Available Operations

//[.doc h3]
//* Render Notices

=== Render Notices

The "/render" operation converts XML procurement notices into user-friendly formats like PDF or HTML, making the data easier to read and share. This API provides operations in two variants. For larger, more complex notices, the asynchronous API should be used to prevent request time-outs.  



==== API Request
[source]
----
POST /v3/notices/render
----

[source]
----
POST /v3/notices/render-async
----

NOTE: Please note that asynchronous rendering is currently unavailable in Preview or Production environments and will result in a 404 Not Found error as an HTTP status code; however, we are working to make this feature accessible soon.


==== Swagger API Endpoints

- **Preview Environment:**  
  * link:https://api.preview.ted.europa.eu/swagger-ui/index.html#/Visualisation/render[Swagger: Access Render Operation]
  * Asynchronous rendering with callback is not yet available but is soon to come.

- **Production Environment:**  
  * link:https://api.ted.europa.eu/swagger-ui/index.html#/Visualisation/render[Swagger: Access Render Operation]
  * Asynchronous rendering with callback is not yet available but is soon to come.


== Who Uses This API

* *Organisations*: Integrating visualised notices into their platforms. 
* *TED developers*: Generating previews for notices. 
* *eNotices2 application*: For the rendering of notices via the web interface in PDF or HTML. 

'''
Explore more about view templates used in rendering https://docs.ted.europa.eu/eforms/latest/viewer-templates/index.html[here]

////
